# fly.toml app configuration file generated for labdevops-9aso-grupo31 on 2023-04-23T18:23:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "labdevops-9aso-grupo31"
primary_region = "gru"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20